# Usa uma imagem oficial do Debian, que tem melhor suporte a GLIBC e Firebird
FROM debian:stable-slim

# Define o diretório de trabalho
WORKDIR /app

# Atualiza pacotes e instala dependências do Firebird e Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    firebird-dev \
    firebird3.0-server \
    firebird3.0-utils \
    libfbclient2 \
    && rm -rf /var/lib/apt/lists/*

# Copia os arquivos do projeto para o contêiner
COPY . .

# Instala as dependências do Python
RUN pip3 install --no-cache-dir -r requirements.txt

# Expor a porta 5000 para o Railway
EXPOSE 5000

# Comando para rodar a aplicação Flask
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
